server:
  port: 8888

spring:
  application:
    name: msvc-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations