server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: student
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**

  application:
    name: msvc-gateway


